
import QtQuick
import qs.modules.theme

QtObject {

    

    readonly property var staticItems: [
        { label: "Network", keywords: "internet wifi connection ethernet ip", section: "network", subSection: "", subLabel: "", icon: Icons.wifiHigh, isIcon: true },
        
        { label: "Bluetooth", keywords: "devices pairing connect", section: "bluetooth", subSection: "", subLabel: "", icon: Icons.bluetooth, isIcon: true },
        
        { label: "Audio Mixer", keywords: "sound volume output input mic speaker", section: "mixer", subSection: "", subLabel: "", icon: Icons.faders, isIcon: true },
        
        { label: "Audio Effects", keywords: "equalizer bass treble easyeffects", section: "effects", subSection: "", subLabel: "", icon: Icons.waveform, isIcon: true },
        
        { label: "Theme", keywords: "appearance look style customize", section: "theme", subSection: "", subLabel: "Theme", icon: Icons.paintBrush, isIcon: true },
        
        { label: "Wallpapers", keywords: "background image picture desktop", section: "theme", subSection: "general", subLabel: "Theme > General", icon: Icons.image, isIcon: true },
        { label: "Tint Icons", keywords: "color icons tint monochrome", section: "theme", subSection: "general", subLabel: "Theme > General", icon: Icons.palette, isIcon: true },
        { label: "Enable Corners", keywords: "rounded corners radius screen", section: "theme", subSection: "general", subLabel: "Theme > General", icon: Icons.cornersOut, isIcon: true },
        { label: "Animation Duration", keywords: "speed fast slow transition", section: "theme", subSection: "general", subLabel: "Theme > General", icon: Icons.clock, isIcon: true },
        { label: "UI Font", keywords: "typography text family size", section: "theme", subSection: "general", subLabel: "Theme > General", icon: Icons.textT, isIcon: true },
        { label: "Roundness", keywords: "radius border curve", section: "theme", subSection: "general", subLabel: "Theme > General", icon: Icons.circle, isIcon: true },
        
        { label: "Shadow Opacity", keywords: "darkness alpha transparency", section: "theme", subSection: "shadow", subLabel: "Theme > Shadow", icon: Icons.drop, isIcon: true },
        { label: "Shadow Blur", keywords: "softness diffusion", section: "theme", subSection: "shadow", subLabel: "Theme > Shadow", icon: Icons.drop, isIcon: true },
        { label: "Shadow Offset", keywords: "position x y direction", section: "theme", subSection: "shadow", subLabel: "Theme > Shadow", icon: Icons.arrowsOutSimple, isIcon: true },

        { label: "Color Scheme", keywords: "palette variant light dark", section: "theme", subSection: "colors", subLabel: "Theme > Colors", icon: Icons.palette, isIcon: true },
        { label: "Color Variant", keywords: "background popup internal bar pane", section: "theme", subSection: "colors", subLabel: "Theme > Colors", icon: Icons.palette, isIcon: true },
        { label: "Background Variant", keywords: "wallpaper desktop color", section: "theme", subSection: "colors", subLabel: "Theme > Colors", icon: Icons.palette, isIcon: true },
        { label: "Popup Variant", keywords: "dialog modal color", section: "theme", subSection: "colors", subLabel: "Theme > Colors", icon: Icons.palette, isIcon: true },
        { label: "Internal BG Variant", keywords: "inside background color", section: "theme", subSection: "colors", subLabel: "Theme > Colors", icon: Icons.palette, isIcon: true },
        { label: "Bar BG Variant", keywords: "taskbar panel color", section: "theme", subSection: "colors", subLabel: "Theme > Colors", icon: Icons.palette, isIcon: true },
        { label: "Pane Variant", keywords: "sidebar panel color", section: "theme", subSection: "colors", subLabel: "Theme > Colors", icon: Icons.palette, isIcon: true },
        { label: "Gradient Mode", keywords: "linear radial halftone", section: "theme", subSection: "colors", subLabel: "Theme > Colors", icon: Icons.palette, isIcon: true },
        { label: "Item Color", keywords: "overbackground surface", section: "theme", subSection: "colors", subLabel: "Theme > Colors", icon: Icons.palette, isIcon: true },
        { label: "Color Opacity", keywords: "alpha transparency", section: "theme", subSection: "colors", subLabel: "Theme > Colors", icon: Icons.palette, isIcon: true },
        { label: "Color Border", keywords: "stroke outline", section: "theme", subSection: "colors", subLabel: "Theme > Colors", icon: Icons.palette, isIcon: true },
        { label: "Gradient Stops", keywords: "color position stops", section: "theme", subSection: "colors", subLabel: "Theme > Colors", icon: Icons.palette, isIcon: true },
        { label: "Gradient Angle", keywords: "direction rotation degrees", section: "theme", subSection: "colors", subLabel: "Theme > Colors", icon: Icons.palette, isIcon: true },

        { label: "System", keywords: "hardware info resources cpu ram", section: "system", subSection: "", subLabel: "System", icon: Icons.circuitry, isIcon: true },
        
        { label: "Prefixes", keywords: "shortcuts launcher quick actions", section: "system", subSection: "prefixes", subLabel: "System > Prefixes", icon: Icons.keyboard, isIcon: true },
        { label: "Clipboard Prefix", keywords: "cc copy paste launcher", section: "system", subSection: "prefixes", subLabel: "System > Prefixes", icon: Icons.keyboard, isIcon: true },
        { label: "Emoji Prefix", keywords: "ee picker launcher", section: "system", subSection: "prefixes", subLabel: "System > Prefixes", icon: Icons.keyboard, isIcon: true },
        { label: "Tmux Prefix", keywords: "tt terminal launcher", section: "system", subSection: "prefixes", subLabel: "System > Prefixes", icon: Icons.keyboard, isIcon: true },
        { label: "Wallpapers Prefix", keywords: "ww background launcher", section: "system", subSection: "prefixes", subLabel: "System > Prefixes", icon: Icons.keyboard, isIcon: true },
        { label: "Notes Prefix", keywords: "nn note launcher", section: "system", subSection: "prefixes", subLabel: "System > Prefixes", icon: Icons.keyboard, isIcon: true },
        
        { label: "Weather Location", keywords: "city country place gps", section: "system", subSection: "weather", subLabel: "System > Weather", icon: Icons.mapPin, isIcon: true },
        { label: "Temperature Unit", keywords: "celsius fahrenheit scale", section: "system", subSection: "weather", subLabel: "System > Weather", icon: Icons.thermometer, isIcon: true },

        { label: "Blur Transition", keywords: "animation speed performance effect", section: "system", subSection: "performance", subLabel: "System > Performance", icon: Icons.lightning, isIcon: true },
        { label: "Window Preview", keywords: "thumbnail overview alt-tab", section: "system", subSection: "performance", subLabel: "System > Performance", icon: Icons.windowsLogo, isIcon: true },
        { label: "Wavy Line", keywords: "animated wave effect performance", section: "system", subSection: "performance", subLabel: "System > Performance", icon: Icons.lightning, isIcon: true },
        
        { label: "System Resources", keywords: "cpu ram memory usage monitor", section: "system", subSection: "system", subLabel: "System > Resources", icon: Icons.circuitry, isIcon: true },

        { label: "Audio Visualizer", keywords: "cava bars media player performance", section: "system", subSection: "performance", subLabel: "System > Performance", icon: Icons.waveform, isIcon: true },

        { label: "Replay Buffer Length", keywords: "recording clip instant replay seconds", section: "system", subSection: "recording", subLabel: "System > Recording", icon: Icons.recordScreen, isIcon: true },

        { label: "Slideshow", keywords: "wallpaper cycle rotate shuffle background", section: "system", subSection: "wallpaper", subLabel: "System > Wallpaper", icon: Icons.image, isIcon: true },
        { label: "Wallpaper Interval", keywords: "slideshow minutes timer background", section: "system", subSection: "wallpaper", subLabel: "System > Wallpaper", icon: Icons.clock, isIcon: true },

        { label: "Auto Theme", keywords: "day night light dark schedule", section: "system", subSection: "daynight", subLabel: "System > Day & Night", icon: Icons.sun, isIcon: true },
        { label: "Night Light Temperature", keywords: "blue light filter warm kelvin", section: "system", subSection: "daynight", subLabel: "System > Day & Night", icon: Icons.nightLight, isIcon: true },

        { label: "Do Not Disturb", keywords: "dnd silent notifications popups mute", section: "system", subSection: "notifications", subLabel: "System > Notifications", icon: Icons.bellSlash, isIcon: true },

        { label: "Pomodoro", keywords: "timer work rest session focus spotify", section: "system", subSection: "pomodoro", subLabel: "System > Pomodoro", icon: Icons.timer, isIcon: true },

        { label: "Idle Settings", keywords: "screen lock timeout sleep suspend", section: "system", subSection: "idle", subLabel: "System > Idle", icon: Icons.moon, isIcon: true },
        { label: "Idle Actions", keywords: "master enable dim lock suspend timers", section: "system", subSection: "idle", subLabel: "System > Idle", icon: Icons.moon, isIcon: true },
        { label: "Lock on Boot", keywords: "lockscreen session start login", section: "system", subSection: "idle", subLabel: "System > Idle", icon: Icons.lock, isIcon: true },
        { label: "Lock on Sleep", keywords: "lockscreen suspend before sleep", section: "system", subSection: "idle", subLabel: "System > Idle", icon: Icons.lock, isIcon: true },
        { label: "Lock After", keywords: "idle timeout lockscreen minutes", section: "system", subSection: "idle", subLabel: "System > Idle", icon: Icons.lock, isIcon: true },
        { label: "Suspend After", keywords: "idle timeout sleep minutes", section: "system", subSection: "idle", subLabel: "System > Idle", icon: Icons.moon, isIcon: true },
        { label: "Lock Command", keywords: "pangu lock screen idle", section: "system", subSection: "idle", subLabel: "System > Idle", icon: Icons.moon, isIcon: true },
        { label: "After Sleep", keywords: "screen on resume idle", section: "system", subSection: "idle", subLabel: "System > Idle", icon: Icons.moon, isIcon: true },
        { label: "Idle Listener", keywords: "timeout brightness screen off suspend", section: "system", subSection: "idle", subLabel: "System > Idle", icon: Icons.moon, isIcon: true },
        
        { label: "Compositor", keywords: "compositor window manager wm", section: "compositor", subSection: "", subLabel: "Compositor", icon: Icons.compositor, isIcon: true },
        
        { label: "Border Size", keywords: "width thickness stroke", section: "compositor", subSection: "general", subLabel: "Compositor > Hyprland", icon: Icons.frameCorners, isIcon: true },
        { label: "Window Gaps", keywords: "spacing margin padding", section: "compositor", subSection: "general", subLabel: "Compositor > Hyprland", icon: Icons.squaresFour, isIcon: true },
        
        { label: "Border Colors", keywords: "active inactive focus", section: "compositor", subSection: "colors", subLabel: "Compositor > Hyprland", icon: Icons.palette, isIcon: true },

        { label: "Shadows Enabled", keywords: "toggle on off", section: "compositor", subSection: "shadows", subLabel: "Compositor > Hyprland", icon: Icons.drop, isIcon: true },
        { label: "Sync Shadow Color", keywords: "match border", section: "compositor", subSection: "shadows", subLabel: "Compositor > Hyprland", icon: Icons.palette, isIcon: true },
        { label: "Sync Shadow Opacity", keywords: "match border alpha", section: "compositor", subSection: "shadows", subLabel: "Compositor > Hyprland", icon: Icons.drop, isIcon: true },
        { label: "Shadow Range", keywords: "blur radius size", section: "compositor", subSection: "shadows", subLabel: "Compositor > Hyprland", icon: Icons.circle, isIcon: true },
        { label: "Shadow Offset", keywords: "position x y move", section: "compositor", subSection: "shadows", subLabel: "Compositor > Hyprland", icon: Icons.arrowsOutSimple, isIcon: true },
        { label: "Shadow Power", keywords: "strength render intensity", section: "compositor", subSection: "shadows", subLabel: "Compositor > Hyprland", icon: Icons.lightning, isIcon: true },
        { label: "Shadow Scale", keywords: "zoom resize", section: "compositor", subSection: "shadows", subLabel: "Compositor > Hyprland", icon: Icons.cornersOut, isIcon: true },

        { label: "Blur Enabled", keywords: "toggle on off transparency", section: "compositor", subSection: "blur", subLabel: "Compositor > Hyprland", icon: Icons.drop, isIcon: true },
        { label: "Blur Size", keywords: "radius amount", section: "compositor", subSection: "blur", subLabel: "Compositor > Hyprland", icon: Icons.circle, isIcon: true },
        { label: "Blur Passes", keywords: "quality iterations", section: "compositor", subSection: "blur", subLabel: "Compositor > Hyprland", icon: Icons.circle, isIcon: true },
        { label: "Blur Xray", keywords: "transparency see through", section: "compositor", subSection: "blur", subLabel: "Compositor > Hyprland", icon: Icons.drop, isIcon: true },
        { label: "Blur New Optimizations", keywords: "performance speed", section: "compositor", subSection: "blur", subLabel: "Compositor > Hyprland", icon: Icons.lightning, isIcon: true },
        { label: "Blur Ignore Opacity", keywords: "transparency alpha", section: "compositor", subSection: "blur", subLabel: "Compositor > Hyprland", icon: Icons.drop, isIcon: true },
        { label: "Blur Ignorealpha", keywords: "explicit transparency", section: "compositor", subSection: "blur", subLabel: "Compositor > Hyprland", icon: Icons.drop, isIcon: true },
        { label: "Blur Ignorealpha Value", keywords: "threshold amount", section: "compositor", subSection: "blur", subLabel: "Compositor > Hyprland", icon: Icons.drop, isIcon: true },
        { label: "Blur Noise", keywords: "grain texture static", section: "compositor", subSection: "blur", subLabel: "Compositor > Hyprland", icon: Icons.drop, isIcon: true },
        { label: "Blur Contrast", keywords: "intensity difference", section: "compositor", subSection: "blur", subLabel: "Compositor > Hyprland", icon: Icons.drop, isIcon: true },
        { label: "Blur Brightness", keywords: "light dark level", section: "compositor", subSection: "blur", subLabel: "Compositor > Hyprland", icon: Icons.drop, isIcon: true },
        { label: "Blur Vibrancy", keywords: "saturation color", section: "compositor", subSection: "blur", subLabel: "Compositor > Hyprland", icon: Icons.drop, isIcon: true },

        { label: "Shell", keywords: "shell panels modules", section: "shell", subSection: "", subLabel: "", icon: Icons.cube, isIcon: true },
        { label: "About", keywords: "about info version pangu", section: "shell", subSection: "about", subLabel: "Shell > About", icon: Icons.cube, isIcon: true },
        
        { label: "Layout Presets", keywords: "layout preset save apply overhaul restore stock", section: "shell", subSection: "presets", subLabel: "Shell > Layout Presets", icon: Icons.layout, isIcon: true },
        
        { label: "Bar", keywords: "panel taskbar top bottom", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.layout, isIcon: true },
        { label: "Bar Position", keywords: "top bottom left right edge", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.layout, isIcon: true },
        { label: "Launcher Icon", keywords: "logo symbol path", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.layout, isIcon: true },
        { label: "Launcher Icon Tint", keywords: "color theme", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.palette, isIcon: true },
        { label: "Launcher Icon Full Tint", keywords: "monochrome color", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.palette, isIcon: true },
        { label: "Launcher Icon Size", keywords: "width height pixels", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.layout, isIcon: true },
        { label: "Pill Style", keywords: "squished roundness radius bar", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.layout, isIcon: true },
        { label: "Bar Style", keywords: "floating docked full width edge bar", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.layout, isIcon: true },
        { label: "Bar Margin", keywords: "gap distance edge offset bar", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.layout, isIcon: true },
        { label: "Bar Spacing", keywords: "gap between widgets buttons bar", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.layout, isIcon: true },
        { label: "Bar Padding", keywords: "inner padding content bar", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.layout, isIcon: true },
        { label: "Clock Position", keywords: "center right time bar", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.clock, isIcon: true },
        { label: "Clock Seconds", keywords: "time seconds precise bar", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.clock, isIcon: true },
        { label: "Clock Date", keywords: "time day month date bar", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.clock, isIcon: true },
        { label: "Launcher Position", keywords: "start end left right bar", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.layout, isIcon: true },
        { label: "Flat Buttons", keywords: "flat icons transparent taskbar bar", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.layout, isIcon: true },
        { label: "Show Workspaces", keywords: "workspace dots indicators bar", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.squaresFour, isIcon: true },
        { label: "Firefox Player", keywords: "browser media music", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.layout, isIcon: true },
        { label: "Bar Auto-hide", keywords: "autohide hide show reveal", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.layout, isIcon: true },
        { label: "Pinned on Startup", keywords: "show visible default", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.layout, isIcon: true },
        { label: "Hover to Reveal", keywords: "mouse show hide edge", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.layout, isIcon: true },
        { label: "Hover Region Height", keywords: "pixels trigger area", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.layout, isIcon: true },
        { label: "Show Pin Button", keywords: "toggle pin unpin", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.layout, isIcon: true },
        { label: "Available on Fullscreen", keywords: "overlay game video", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.layout, isIcon: true },
        { label: "Show Running Indicators", keywords: "dots active apps", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.layout, isIcon: true },
        { label: "Show Overview Button", keywords: "workspace switcher", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.layout, isIcon: true },
        { label: "Bar Screens", keywords: "monitor display eDP", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.layout, isIcon: true },
        
        { label: "Frame", keywords: "border screen edge thickness contain bar", section: "shell", subSection: "frame", subLabel: "Shell > Frame", icon: Icons.frameCorners, isIcon: true },

        { label: "Notch", keywords: "island dynamic island center", section: "shell", subSection: "notch", subLabel: "Shell > Notch", icon: Icons.layout, isIcon: true },
        { label: "Notch Hover Expansion Delay", keywords: "expand media player hover time", section: "shell", subSection: "notch", subLabel: "Shell > Notch", icon: Icons.layout, isIcon: true },
        { label: "Notch Show User", keywords: "avatar user host hide", section: "shell", subSection: "notch", subLabel: "Shell > Notch", icon: Icons.user, isIcon: true },
        { label: "Notch Show Media", keywords: "player music hide", section: "shell", subSection: "notch", subLabel: "Shell > Notch", icon: Icons.layout, isIcon: true },
        { label: "Notch Show Notification Indicator", keywords: "bell notifications hide", section: "shell", subSection: "notch", subLabel: "Shell > Notch", icon: Icons.bell, isIcon: true },
        
        { label: "Workspaces", keywords: "virtual desktop spaces", section: "shell", subSection: "workspaces", subLabel: "Shell > Workspaces", icon: Icons.squaresFour, isIcon: true },
        { label: "Workspaces Shown", keywords: "number count visible", section: "shell", subSection: "workspaces", subLabel: "Shell > Workspaces", icon: Icons.squaresFour, isIcon: true },
        { label: "Show App Icons", keywords: "application thumbnail workspace", section: "shell", subSection: "workspaces", subLabel: "Shell > Workspaces", icon: Icons.squaresFour, isIcon: true },
        { label: "Always Show Numbers", keywords: "workspace label index", section: "shell", subSection: "workspaces", subLabel: "Shell > Workspaces", icon: Icons.squaresFour, isIcon: true },
        { label: "Show Numbers", keywords: "workspace label index", section: "shell", subSection: "workspaces", subLabel: "Shell > Workspaces", icon: Icons.squaresFour, isIcon: true },
        { label: "Dynamic Workspaces", keywords: "auto add remove flexible", section: "shell", subSection: "workspaces", subLabel: "Shell > Workspaces", icon: Icons.squaresFour, isIcon: true },
        
        { label: "Overview", keywords: "expose mission control windows", section: "shell", subSection: "overview", subLabel: "Shell > Overview", icon: Icons.squaresFour, isIcon: true },
        { label: "Overview Rows", keywords: "grid layout vertical", section: "shell", subSection: "overview", subLabel: "Shell > Overview", icon: Icons.squaresFour, isIcon: true },
        { label: "Overview Columns", keywords: "grid layout horizontal", section: "shell", subSection: "overview", subLabel: "Shell > Overview", icon: Icons.squaresFour, isIcon: true },
        { label: "Overview Scale", keywords: "zoom size preview", section: "shell", subSection: "overview", subLabel: "Shell > Overview", icon: Icons.squaresFour, isIcon: true },
        { label: "Overview Workspace Spacing", keywords: "gap margin distance", section: "shell", subSection: "overview", subLabel: "Shell > Overview", icon: Icons.squaresFour, isIcon: true },
        
        { label: "Dashboard", keywords: "menu panel widgets dashboard", section: "shell", subSection: "dashboard", subLabel: "Shell > Dashboard", icon: Icons.layout, isIcon: true },
        { label: "Dashboard Width", keywords: "size width menu dashboard", section: "shell", subSection: "dashboard", subLabel: "Shell > Dashboard", icon: Icons.layout, isIcon: true },
        { label: "Dashboard Height", keywords: "size height menu dashboard", section: "shell", subSection: "dashboard", subLabel: "Shell > Dashboard", icon: Icons.layout, isIcon: true },
        { label: "Dashboard Tab Rail", keywords: "tabs show hide rail dashboard", section: "shell", subSection: "dashboard", subLabel: "Shell > Dashboard", icon: Icons.layout, isIcon: true },
        { label: "Dashboard Tab Position", keywords: "tabs left right top bottom rail dashboard", section: "shell", subSection: "dashboard", subLabel: "Shell > Dashboard", icon: Icons.layout, isIcon: true },
        { label: "Dashboard Widgets Tab", keywords: "show hide widgets tab dashboard", section: "shell", subSection: "dashboard", subLabel: "Shell > Dashboard", icon: Icons.widgets, isIcon: true },
        { label: "Dashboard Wallpapers Tab", keywords: "show hide wallpapers tab dashboard", section: "shell", subSection: "dashboard", subLabel: "Shell > Dashboard", icon: Icons.wallpapers, isIcon: true },
        { label: "Dashboard Metrics Tab", keywords: "show hide metrics tab dashboard", section: "shell", subSection: "dashboard", subLabel: "Shell > Dashboard", icon: Icons.heartbeat, isIcon: true },
        { label: "Dashboard Background Opacity", keywords: "transparency opacity background dashboard", section: "shell", subSection: "dashboard", subLabel: "Shell > Dashboard", icon: Icons.layout, isIcon: true },
        
        { label: "Launcher", keywords: "app drawer search menu launch", section: "shell", subSection: "launcher", subLabel: "Shell > Launcher", icon: Icons.apps, isIcon: true },
        { label: "Launcher Width", keywords: "size width app drawer launcher", section: "shell", subSection: "launcher", subLabel: "Shell > Launcher", icon: Icons.layout, isIcon: true },
        { label: "Launcher Height", keywords: "size height app drawer launcher", section: "shell", subSection: "launcher", subLabel: "Shell > Launcher", icon: Icons.layout, isIcon: true },
        { label: "Launcher App Comments", keywords: "show hide comment subtitle app drawer", section: "shell", subSection: "launcher", subLabel: "Shell > Launcher", icon: Icons.layout, isIcon: true },
        { label: "Launcher Sort by Usage", keywords: "sort frequent apps usage launcher", section: "shell", subSection: "launcher", subLabel: "Shell > Launcher", icon: Icons.layout, isIcon: true },
        
        { label: "Dock", keywords: "taskbar launcher apps favorites", section: "shell", subSection: "dock", subLabel: "Shell > Dock", icon: Icons.layout, isIcon: true },
        { label: "Dock Enabled", keywords: "show hide toggle", section: "shell", subSection: "dock", subLabel: "Shell > Dock", icon: Icons.layout, isIcon: true },
        { label: "Dock Mode", keywords: "default floating integrated style", section: "shell", subSection: "dock", subLabel: "Shell > Dock", icon: Icons.layout, isIcon: true },
        { label: "Dock Position", keywords: "left bottom right edge", section: "shell", subSection: "dock", subLabel: "Shell > Dock", icon: Icons.layout, isIcon: true },
        { label: "Dock Height", keywords: "size thickness pixels", section: "shell", subSection: "dock", subLabel: "Shell > Dock", icon: Icons.layout, isIcon: true },
        { label: "Dock Icon Size", keywords: "width height pixels apps", section: "shell", subSection: "dock", subLabel: "Shell > Dock", icon: Icons.layout, isIcon: true },
        { label: "Dock Spacing", keywords: "gap between icons", section: "shell", subSection: "dock", subLabel: "Shell > Dock", icon: Icons.layout, isIcon: true },
        { label: "Dock Margin", keywords: "edge distance offset", section: "shell", subSection: "dock", subLabel: "Shell > Dock", icon: Icons.layout, isIcon: true },
        { label: "Dock Hover Region Height", keywords: "trigger area pixels", section: "shell", subSection: "dock", subLabel: "Shell > Dock", icon: Icons.layout, isIcon: true },
        { label: "Dock Pinned on Startup", keywords: "show visible default", section: "shell", subSection: "dock", subLabel: "Shell > Dock", icon: Icons.layout, isIcon: true },
        
        { label: "Lockscreen", keywords: "lock screen password login", section: "shell", subSection: "lockscreen", subLabel: "Shell > Lockscreen", icon: Icons.lock, isIcon: true },
        
        { label: "Shell System", keywords: "config settings pangu", section: "shell", subSection: "system", subLabel: "Shell > System", icon: Icons.circuitry, isIcon: true },
        { label: "Light Mode", keywords: "Light Mode general", section: "theme", subSection: "general", subLabel: "Theme > General", icon: Icons.faders, isIcon: true },
        { label: "OLED Mode", keywords: "OLED Mode general", section: "theme", subSection: "general", subLabel: "Theme > General", icon: Icons.faders, isIcon: true },
        { label: "Colors Follow Wallpaper", keywords: "Colors Follow Wallpaper colors", section: "theme", subSection: "colors", subLabel: "Theme > Colors", icon: Icons.faders, isIcon: true },
        { label: "Clipboard", keywords: "Clipboard prefixes", section: "system", subSection: "prefixes", subLabel: "System > Prefixes", icon: Icons.faders, isIcon: true },
        { label: "Emoji", keywords: "Emoji prefixes", section: "system", subSection: "prefixes", subLabel: "System > Prefixes", icon: Icons.faders, isIcon: true },
        { label: "Tmux", keywords: "Tmux prefixes", section: "system", subSection: "prefixes", subLabel: "System > Prefixes", icon: Icons.faders, isIcon: true },
        { label: "Wallpapers", keywords: "Wallpapers prefixes", section: "system", subSection: "prefixes", subLabel: "System > Prefixes", icon: Icons.faders, isIcon: true },
        { label: "Notes", keywords: "Notes prefixes", section: "system", subSection: "prefixes", subLabel: "System > Prefixes", icon: Icons.faders, isIcon: true },
        { label: "Celsius", keywords: "Celsius weather", section: "system", subSection: "weather", subLabel: "System > Weather", icon: Icons.faders, isIcon: true },
        { label: "Fahrenheit", keywords: "Fahrenheit weather", section: "system", subSection: "weather", subLabel: "System > Weather", icon: Icons.faders, isIcon: true },
        { label: "Persist Dashboard Tabs", keywords: "Persist Dashboard Tabs performance", section: "system", subSection: "performance", subLabel: "System > Performance", icon: Icons.faders, isIcon: true },
        { label: "Max Persistent Tabs", keywords: "Max Persistent Tabs performance", section: "system", subSection: "performance", subLabel: "System > Performance", icon: Icons.faders, isIcon: true },
        { label: "Disable Cover Art Rotation", keywords: "Disable Cover Art Rotation performance", section: "system", subSection: "performance", subLabel: "System > Performance", icon: Icons.faders, isIcon: true },
        { label: "Lock When Idle", keywords: "Lock When Idle idle", section: "system", subSection: "idle", subLabel: "System > Idle", icon: Icons.faders, isIcon: true },
        { label: "Screen Off When Idle", keywords: "Screen Off When Idle idle", section: "system", subSection: "idle", subLabel: "System > Idle", icon: Icons.faders, isIcon: true },
        { label: "Screen Off After", keywords: "Screen Off After idle", section: "system", subSection: "idle", subLabel: "System > Idle", icon: Icons.faders, isIcon: true },
        { label: "Suspend When Idle", keywords: "Suspend When Idle idle", section: "system", subSection: "idle", subLabel: "System > Idle", icon: Icons.faders, isIcon: true },
        { label: "Lock Cmd", keywords: "Lock Cmd idle", section: "system", subSection: "idle", subLabel: "System > Idle", icon: Icons.faders, isIcon: true },
        { label: "Timeout (s)", keywords: "Timeout (s) idle", section: "system", subSection: "idle", subLabel: "System > Idle", icon: Icons.faders, isIcon: true },
        { label: "On Timeout", keywords: "On Timeout idle", section: "system", subSection: "idle", subLabel: "System > Idle", icon: Icons.faders, isIcon: true },
        { label: "On Resume", keywords: "On Resume idle", section: "system", subSection: "idle", subLabel: "System > Idle", icon: Icons.faders, isIcon: true },
        { label: "Shuffle", keywords: "Shuffle wallpaper", section: "system", subSection: "wallpaper", subLabel: "System > Wallpaper", icon: Icons.faders, isIcon: true },
        { label: "Interval", keywords: "Interval wallpaper", section: "system", subSection: "wallpaper", subLabel: "System > Wallpaper", icon: Icons.faders, isIcon: true },
        { label: "Use Sunrise and Sunset", keywords: "Use Sunrise and Sunset daynight", section: "system", subSection: "daynight", subLabel: "System > Daynight", icon: Icons.faders, isIcon: true },
        { label: "Day Starts", keywords: "Day Starts daynight", section: "system", subSection: "daynight", subLabel: "System > Daynight", icon: Icons.faders, isIcon: true },
        { label: "Night Starts", keywords: "Night Starts daynight", section: "system", subSection: "daynight", subLabel: "System > Daynight", icon: Icons.faders, isIcon: true },
        { label: "Work Session", keywords: "Work Session pomodoro", section: "system", subSection: "pomodoro", subLabel: "System > Pomodoro", icon: Icons.faders, isIcon: true },
        { label: "Rest Session", keywords: "Rest Session pomodoro", section: "system", subSection: "pomodoro", subLabel: "System > Pomodoro", icon: Icons.faders, isIcon: true },
        { label: "Auto Start Next", keywords: "Auto Start Next pomodoro", section: "system", subSection: "pomodoro", subLabel: "System > Pomodoro", icon: Icons.faders, isIcon: true },
        { label: "Sync Spotify", keywords: "Sync Spotify pomodoro", section: "system", subSection: "pomodoro", subLabel: "System > Pomodoro", icon: Icons.faders, isIcon: true },
        { label: "Sync Border Size", keywords: "Sync Border Size general", section: "compositor", subSection: "general", subLabel: "Compositor > General", icon: Icons.faders, isIcon: true },
        { label: "Sync Rounding", keywords: "Sync Rounding general", section: "compositor", subSection: "general", subLabel: "Compositor > General", icon: Icons.faders, isIcon: true },
        { label: "Rounding", keywords: "Rounding general", section: "compositor", subSection: "general", subLabel: "Compositor > General", icon: Icons.faders, isIcon: true },
        { label: "Gaps In", keywords: "Gaps In general", section: "compositor", subSection: "general", subLabel: "Compositor > General", icon: Icons.faders, isIcon: true },
        { label: "Gaps Out", keywords: "Gaps Out general", section: "compositor", subSection: "general", subLabel: "Compositor > General", icon: Icons.faders, isIcon: true },
        { label: "Border Angle", keywords: "Border Angle general", section: "compositor", subSection: "general", subLabel: "Compositor > General", icon: Icons.faders, isIcon: true },
        { label: "Inactive Angle", keywords: "Inactive Angle general", section: "compositor", subSection: "general", subLabel: "Compositor > General", icon: Icons.faders, isIcon: true },
        { label: "Sync Border Color", keywords: "Sync Border Color colors", section: "compositor", subSection: "colors", subLabel: "Compositor > Colors", icon: Icons.faders, isIcon: true },
        { label: "Active Border", keywords: "Active Border colors", section: "compositor", subSection: "colors", subLabel: "Compositor > Colors", icon: Icons.faders, isIcon: true },
        { label: "Inactive Border", keywords: "Inactive Border colors", section: "compositor", subSection: "colors", subLabel: "Compositor > Colors", icon: Icons.faders, isIcon: true },
        { label: "Enabled", keywords: "Enabled shadows", section: "compositor", subSection: "shadows", subLabel: "Compositor > Shadows", icon: Icons.faders, isIcon: true },
        { label: "Sync Color", keywords: "Sync Color shadows", section: "compositor", subSection: "shadows", subLabel: "Compositor > Shadows", icon: Icons.faders, isIcon: true },
        { label: "Sync Opacity", keywords: "Sync Opacity shadows", section: "compositor", subSection: "shadows", subLabel: "Compositor > Shadows", icon: Icons.faders, isIcon: true },
        { label: "Range", keywords: "Range shadows", section: "compositor", subSection: "shadows", subLabel: "Compositor > Shadows", icon: Icons.faders, isIcon: true },
        { label: "Offset X", keywords: "Offset X shadows", section: "compositor", subSection: "shadows", subLabel: "Compositor > Shadows", icon: Icons.faders, isIcon: true },
        { label: "Offset Y", keywords: "Offset Y shadows", section: "compositor", subSection: "shadows", subLabel: "Compositor > Shadows", icon: Icons.faders, isIcon: true },
        { label: "Render Power", keywords: "Render Power shadows", section: "compositor", subSection: "shadows", subLabel: "Compositor > Shadows", icon: Icons.faders, isIcon: true },
        { label: "Scale", keywords: "Scale shadows", section: "compositor", subSection: "shadows", subLabel: "Compositor > Shadows", icon: Icons.faders, isIcon: true },
        { label: "Opacity", keywords: "Opacity shadows", section: "compositor", subSection: "shadows", subLabel: "Compositor > Shadows", icon: Icons.faders, isIcon: true },
        { label: "Sharp", keywords: "Sharp shadows", section: "compositor", subSection: "shadows", subLabel: "Compositor > Shadows", icon: Icons.faders, isIcon: true },
        { label: "Size", keywords: "Size blur", section: "compositor", subSection: "blur", subLabel: "Compositor > Blur", icon: Icons.faders, isIcon: true },
        { label: "Passes", keywords: "Passes blur", section: "compositor", subSection: "blur", subLabel: "Compositor > Blur", icon: Icons.faders, isIcon: true },
        { label: "Xray", keywords: "Xray blur", section: "compositor", subSection: "blur", subLabel: "Compositor > Blur", icon: Icons.faders, isIcon: true },
        { label: "New Optimizations", keywords: "New Optimizations blur", section: "compositor", subSection: "blur", subLabel: "Compositor > Blur", icon: Icons.faders, isIcon: true },
        { label: "Blur Special Workspaces", keywords: "Blur Special Workspaces blur", section: "compositor", subSection: "blur", subLabel: "Compositor > Blur", icon: Icons.faders, isIcon: true },
        { label: "Blur Popups", keywords: "Blur Popups blur", section: "compositor", subSection: "blur", subLabel: "Compositor > Blur", icon: Icons.faders, isIcon: true },
        { label: "Ignore Opacity", keywords: "Ignore Opacity blur", section: "compositor", subSection: "blur", subLabel: "Compositor > Blur", icon: Icons.faders, isIcon: true },
        { label: "Explicit Ignorealpha", keywords: "Explicit Ignorealpha blur", section: "compositor", subSection: "blur", subLabel: "Compositor > Blur", icon: Icons.faders, isIcon: true },
        { label: "Ignorealpha Value", keywords: "Ignorealpha Value blur", section: "compositor", subSection: "blur", subLabel: "Compositor > Blur", icon: Icons.faders, isIcon: true },
        { label: "Noise", keywords: "Noise blur", section: "compositor", subSection: "blur", subLabel: "Compositor > Blur", icon: Icons.faders, isIcon: true },
        { label: "Contrast", keywords: "Contrast blur", section: "compositor", subSection: "blur", subLabel: "Compositor > Blur", icon: Icons.faders, isIcon: true },
        { label: "Brightness", keywords: "Brightness blur", section: "compositor", subSection: "blur", subLabel: "Compositor > Blur", icon: Icons.faders, isIcon: true },
        { label: "Vibrancy", keywords: "Vibrancy blur", section: "compositor", subSection: "blur", subLabel: "Compositor > Blur", icon: Icons.faders, isIcon: true },
        { label: "Bar", keywords: "Bar", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.faders, isIcon: true },
        { label: "Bar Height (0 = auto)", keywords: "Bar Height (0 = auto) bar", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.faders, isIcon: true },
        { label: "Use 12h Format", keywords: "Use 12h Format bar", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.faders, isIcon: true },
        { label: "Show Seconds", keywords: "Show Seconds bar", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.faders, isIcon: true },
        { label: "Show Date", keywords: "Show Date bar", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.faders, isIcon: true },
        { label: "Enable Firefox Player", keywords: "Enable Firefox Player bar", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.faders, isIcon: true },
        { label: "Split on Centered Layout", keywords: "Split on Centered Layout bar", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.faders, isIcon: true },
        { label: "Split Gap Padding", keywords: "Split Gap Padding bar", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.faders, isIcon: true },
        { label: "Hide Delay", keywords: "Hide Delay bar", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.faders, isIcon: true },
        { label: "Screens", keywords: "Screens bar", section: "shell", subSection: "bar", subLabel: "Shell > Bar", icon: Icons.faders, isIcon: true },
        { label: "Enabled", keywords: "Enabled frame", section: "shell", subSection: "frame", subLabel: "Shell > Frame", icon: Icons.faders, isIcon: true },
        { label: "Thickness", keywords: "Thickness frame", section: "shell", subSection: "frame", subLabel: "Shell > Frame", icon: Icons.faders, isIcon: true },
        { label: "Contain Bar", keywords: "Contain Bar frame", section: "shell", subSection: "frame", subLabel: "Shell > Frame", icon: Icons.faders, isIcon: true },
        { label: "Keep Bar Shadow", keywords: "Keep Bar Shadow frame", section: "shell", subSection: "frame", subLabel: "Shell > Frame", icon: Icons.faders, isIcon: true },
        { label: "Keep Bar Border", keywords: "Keep Bar Border frame", section: "shell", subSection: "frame", subLabel: "Shell > Frame", icon: Icons.faders, isIcon: true },
        { label: "Split Side", keywords: "Split Side notch", section: "shell", subSection: "notch", subLabel: "Shell > Notch", icon: Icons.faders, isIcon: true },
        { label: "Hover Expansion Delay", keywords: "Hover Expansion Delay notch", section: "shell", subSection: "notch", subLabel: "Shell > Notch", icon: Icons.faders, isIcon: true },
        { label: "Keep Hidden", keywords: "Keep Hidden notch", section: "shell", subSection: "notch", subLabel: "Shell > Notch", icon: Icons.faders, isIcon: true },
        { label: "Disable Hover Expansion", keywords: "Disable Hover Expansion notch", section: "shell", subSection: "notch", subLabel: "Shell > Notch", icon: Icons.faders, isIcon: true },
        { label: "Show User", keywords: "Show User notch", section: "shell", subSection: "notch", subLabel: "Shell > Notch", icon: Icons.faders, isIcon: true },
        { label: "Show Media Player", keywords: "Show Media Player notch", section: "shell", subSection: "notch", subLabel: "Shell > Notch", icon: Icons.faders, isIcon: true },
        { label: "Show Notification Indicator", keywords: "Show Notification Indicator notch", section: "shell", subSection: "notch", subLabel: "Shell > Notch", icon: Icons.faders, isIcon: true },
        { label: "Custom Text", keywords: "Custom Text notch", section: "shell", subSection: "notch", subLabel: "Shell > Notch", icon: Icons.faders, isIcon: true },
        { label: "Shown", keywords: "Shown workspaces", section: "shell", subSection: "workspaces", subLabel: "Shell > Workspaces", icon: Icons.faders, isIcon: true },
        { label: "Dynamic", keywords: "Dynamic workspaces", section: "shell", subSection: "workspaces", subLabel: "Shell > Workspaces", icon: Icons.faders, isIcon: true },
        { label: "Layout", keywords: "Layout overview", section: "shell", subSection: "overview", subLabel: "Shell > Overview", icon: Icons.faders, isIcon: true },
        { label: "Rows", keywords: "Rows overview", section: "shell", subSection: "overview", subLabel: "Shell > Overview", icon: Icons.faders, isIcon: true },
        { label: "Columns", keywords: "Columns overview", section: "shell", subSection: "overview", subLabel: "Shell > Overview", icon: Icons.faders, isIcon: true },
        { label: "Workspace Spacing", keywords: "Workspace Spacing overview", section: "shell", subSection: "overview", subLabel: "Shell > Overview", icon: Icons.faders, isIcon: true },
        { label: "Dashboard Width (0 = auto)", keywords: "Dashboard Width (0 = auto) dashboard", section: "shell", subSection: "dashboard", subLabel: "Shell > Dashboard", icon: Icons.faders, isIcon: true },
        { label: "Dashboard Height (0 = auto)", keywords: "Dashboard Height (0 = auto) dashboard", section: "shell", subSection: "dashboard", subLabel: "Shell > Dashboard", icon: Icons.faders, isIcon: true },
        { label: "Show Tab Rail", keywords: "Show Tab Rail dashboard", section: "shell", subSection: "dashboard", subLabel: "Shell > Dashboard", icon: Icons.faders, isIcon: true },
        { label: "Tab Rail Position", keywords: "Tab Rail Position dashboard", section: "shell", subSection: "dashboard", subLabel: "Shell > Dashboard", icon: Icons.faders, isIcon: true },
        { label: "Show Widgets Tab", keywords: "Show Widgets Tab dashboard", section: "shell", subSection: "dashboard", subLabel: "Shell > Dashboard", icon: Icons.faders, isIcon: true },
        { label: "Show Wallpapers Tab", keywords: "Show Wallpapers Tab dashboard", section: "shell", subSection: "dashboard", subLabel: "Shell > Dashboard", icon: Icons.faders, isIcon: true },
        { label: "Show Metrics Tab", keywords: "Show Metrics Tab dashboard", section: "shell", subSection: "dashboard", subLabel: "Shell > Dashboard", icon: Icons.faders, isIcon: true },
        { label: "Background Opacity", keywords: "Background Opacity dashboard", section: "shell", subSection: "dashboard", subLabel: "Shell > Dashboard", icon: Icons.faders, isIcon: true },
        { label: "Launcher Width (0 = auto)", keywords: "Launcher Width (0 = auto) launcher", section: "shell", subSection: "launcher", subLabel: "Shell > Launcher", icon: Icons.faders, isIcon: true },
        { label: "Launcher Height (0 = auto)", keywords: "Launcher Height (0 = auto) launcher", section: "shell", subSection: "launcher", subLabel: "Shell > Launcher", icon: Icons.faders, isIcon: true },
        { label: "Show App Comments", keywords: "Show App Comments launcher", section: "shell", subSection: "launcher", subLabel: "Shell > Launcher", icon: Icons.faders, isIcon: true },
        { label: "Sort by Usage", keywords: "Sort by Usage launcher", section: "shell", subSection: "launcher", subLabel: "Shell > Launcher", icon: Icons.faders, isIcon: true },
        { label: "Position", keywords: "Position dock", section: "shell", subSection: "dock", subLabel: "Shell > Dock", icon: Icons.faders, isIcon: true },
        { label: "Theme", keywords: "Theme dock", section: "shell", subSection: "dock", subLabel: "Shell > Dock", icon: Icons.faders, isIcon: true },
        { label: "Height", keywords: "Height dock", section: "shell", subSection: "dock", subLabel: "Shell > Dock", icon: Icons.faders, isIcon: true },
        { label: "Icon Size", keywords: "Icon Size dock", section: "shell", subSection: "dock", subLabel: "Shell > Dock", icon: Icons.faders, isIcon: true },
        { label: "Spacing", keywords: "Spacing dock", section: "shell", subSection: "dock", subLabel: "Shell > Dock", icon: Icons.faders, isIcon: true },
        { label: "Margin", keywords: "Margin dock", section: "shell", subSection: "dock", subLabel: "Shell > Dock", icon: Icons.faders, isIcon: true },
        { label: "Hover Region", keywords: "Hover Region dock", section: "shell", subSection: "dock", subLabel: "Shell > Dock", icon: Icons.faders, isIcon: true },
        { label: "Lock on Boot", keywords: "Lock on Boot lockscreen", section: "shell", subSection: "lockscreen", subLabel: "Shell > Lockscreen", icon: Icons.faders, isIcon: true },
        { label: "Show Clock", keywords: "Show Clock lockscreen", section: "shell", subSection: "lockscreen", subLabel: "Shell > Lockscreen", icon: Icons.faders, isIcon: true },
        { label: "Show Avatar", keywords: "Show Avatar lockscreen", section: "shell", subSection: "lockscreen", subLabel: "Shell > Lockscreen", icon: Icons.faders, isIcon: true },
        { label: "Show Username", keywords: "Show Username lockscreen", section: "shell", subSection: "lockscreen", subLabel: "Shell > Lockscreen", icon: Icons.faders, isIcon: true },
        { label: "Blur Wallpaper", keywords: "Blur Wallpaper lockscreen", section: "shell", subSection: "lockscreen", subLabel: "Shell > Lockscreen", icon: Icons.faders, isIcon: true },
        { label: "Dim Strength", keywords: "Dim Strength lockscreen", section: "shell", subSection: "lockscreen", subLabel: "Shell > Lockscreen", icon: Icons.faders, isIcon: true },
        { label: "Width", keywords: "Width osd", section: "shell", subSection: "osd", subLabel: "Shell > Osd", icon: Icons.faders, isIcon: true },
        { label: "Icon Style", keywords: "Icon Style osd", section: "shell", subSection: "osd", subLabel: "Shell > Osd", icon: Icons.faders, isIcon: true },
        { label: "Show Percentage", keywords: "Show Percentage osd", section: "shell", subSection: "osd", subLabel: "Shell > Osd", icon: Icons.faders, isIcon: true },
        { label: "Show Slider", keywords: "Show Slider osd", section: "shell", subSection: "osd", subLabel: "Shell > Osd", icon: Icons.faders, isIcon: true },
        { label: "English", keywords: "English system", section: "shell", subSection: "system", subLabel: "Shell > System", icon: Icons.faders, isIcon: true },
        { label: "Spanish", keywords: "Spanish system", section: "shell", subSection: "system", subLabel: "Shell > System", icon: Icons.faders, isIcon: true },
        { label: "Latin", keywords: "Latin system", section: "shell", subSection: "system", subLabel: "Shell > System", icon: Icons.faders, isIcon: true },
        { label: "Japanese", keywords: "Japanese system", section: "shell", subSection: "system", subLabel: "Shell > System", icon: Icons.faders, isIcon: true },
        { label: "Chinese (Simplified)", keywords: "Chinese (Simplified) system", section: "shell", subSection: "system", subLabel: "Shell > System", icon: Icons.faders, isIcon: true },
        { label: "Chinese (Traditional)", keywords: "Chinese (Traditional) system", section: "shell", subSection: "system", subLabel: "Shell > System", icon: Icons.faders, isIcon: true },
        { label: "Korean", keywords: "Korean system", section: "shell", subSection: "system", subLabel: "Shell > System", icon: Icons.faders, isIcon: true }
    ]

    readonly property var items: staticItems
}
